### ISSUE TITLE
Major Code Refactoring

### ISSUE THREAD

**Issue by aarora08** [WK-M/SD_ModuleCCNYSD2#2]
I suggest restructuring of code, splitting functions into smaller files, and adding a CI/CD pipeline along with a dependency bot. @Denisolt please add further suggestions. 

@WK-M Thanks

**Comment by Denisolt** [comment]
@aarora08 agreed, especially the file naming convention looks odd to me. Maybe this resource will be helpful - https://www.arduino.cc/en/Reference/StyleGuide

Also, don't wanna be that guy, but @WK-M `// 115200 for GPS, probably need to use 115200 ` doesn't look like an appropriate comment.

**Comment by aarora08** [comment]
Can we switch to Microcontrollers? We can look at [ESP8266](https://www.instructables.com/id/ESP8266-As-a-Microcontroller/)

**Comment by Denisolt** [comment]
> Can we switch to Microcontrollers? We can look at [ESP8266](https://www.instructables.com/id/ESP8266-As-a-Microcontroller/)

Please open a different issue for this topic.

**Comment by WK-Kz** [comment]
ESP8266 will require another module in order to have this project working as intended. Currently, any type of telemetry will be done through LoRA.
